### ISSUE TITLE
hooks（一）问题

### ISSUE THREAD

**Issue by vuvivian** [tuture-dev/covid-19-with-hooks#1]
第一篇的实战，CountriesChart组件在第一次渲染的时候获取到的data值是[].
![image](https://user-images.githubusercontent.com/28998321/81272527-2e95bc00-9080-11ea-851e-10876378f275.png)

**Comment by mrcfps** [comment]
@vuvivian 请问问题解决了吗？可能是因为 NovelCOVID 19 API 偶尔出了点问题~当然这里如果做一下数据合法性的校验就更好了。

**Comment by vuvivian** [comment]
> @vuvivian 请问问题解决了吗？可能是因为 NovelCOVID 19 API 偶尔出了点问题~当然这里如果做一下数据合法性的校验就更好了。

解决了
